### ISSUE TITLE
idk how can i deploy it on replit or netlify

### ISSUE THREAD

**Issue by ghost** [SOKHUONG/discord-clone#7]
PLEASE HELP ME idk how can i deploy it on replit or netlify 
`11:12:00 PM: ​
11:12:00 PM: (build.command completed in 34.1s)
11:12:00 PM: ​
11:12:00 PM: ────────────────────────────────────────────────────────────────
11:12:00 PM:   2. Deploy site                                                
11:12:00 PM: ────────────────────────────────────────────────────────────────
11:12:00 PM: ​
11:12:00 PM: ​
11:12:00 PM: ────────────────────────────────────────────────────────────────
11:12:00 PM:   Configuration error                                           
11:12:00 PM: ────────────────────────────────────────────────────────────────
11:12:00 PM: ​
11:12:00 PM:   Error message
11:12:00 PM:   Deploy did not succeed: Deploy directory 'dist' does not exist
11:12:00 PM: ​
11:12:00 PM:   Resolved config
11:12:00 PM:   build:
11:12:00 PM:     command: npm run build
11:12:00 PM:     commandOrigin: ui
11:12:00 PM:     publish: /opt/build/repo/dist
11:12:00 PM:   functions:
11:12:00 PM:     '*': {}
11:12:01 PM: Caching artifacts
11:12:01 PM: Started saving node modules
11:12:01 PM: Finished saving node modules
11:12:01 PM: Started saving build plugins
11:12:01 PM: Finished saving build plugins
11:12:01 PM: Started saving pip cache
11:12:01 PM: Finished saving pip cache
11:12:01 PM: Started saving emacs cask dependencies
11:12:01 PM: Finished saving emacs cask dependencies
11:12:01 PM: Started saving maven dependencies
11:12:01 PM: Finished saving maven dependencies
11:12:01 PM: Started saving boot dependencies
11:12:01 PM: Finished saving boot dependencies
11:12:01 PM: Started saving rust rustup cache
11:12:01 PM: Finished saving rust rustup cache
11:12:01 PM: Started saving go dependencies
11:12:01 PM: Finished saving go dependencies
11:12:03 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:12:04 PM: Creating deploy upload records
11:12:04 PM: Failing build: Failed to build site
11:12:04 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
11:12:04 PM: Finished processing build request in 1m18.351409859s`

**Comment by SOKHUONG** [comment]
Netlify
Sorry, I just check the issue
Change command:` npm run build` to `npm run generate`
that should work

**Comment by ghost** [comment]
Ok it is fine. Let me try it :)
